---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: backend-staging
  namespace: flux-system
spec:
  chart:
    spec:
      chart: backend/helm/backend
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-demo-microservices
  interval: 30s
  targetNamespace: staging
  values:
    image:
      tag: 0.1.1
    service:
      type: ClusterIP
    #replicaCount: 2
